### ISSUE TITLE
USB format error ish...

### ISSUE THREAD

**Issue by viydinuyde** [aaronnguyen/osid-python3#7]
I cant access the data inside my USB in a windows system after the process is completed.But i seem to have no issue on a Unix system.Any way to solve this??
Can you mount em as fat-32 by default?or smthn?

**Comment by aaronnguyen** [comment]
That's expected. It is a Linux filesystem, so Windows won't be able to access it natively.


I've personally never mounted a RPi SD card in Windows, but maybe give this stackoverflow answer a try: [accessing-raspbian-filesystem-on-sd-card-via-usb-connection-from-windows](https://stackoverflow.com/questions/24167867/accessing-raspbian-filesystem-on-sd-card-via-usb-connection-from-windows).
